version: '3.3'
services:
  mongodb:
    image: bitnami/mongodb:6.0.4
    ports:
      - "27017:27017"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - axon-server-plugin-data-protection

  vault:
    image: vault:latest
    hostname: vault
    ports:
      - '8200:8200'
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=localVaultToken
    networks:
      - axon-server-plugin-data-protection

networks:
  axon-server-plugin-data-protection: